
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const $=id=>document.getElementById(id);
const money=v=>v===0?'No charge':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(v);

const MODULE_LABELS={tyre:'Tyre / wheel exploded view',brake:'Brake pad + disc exploded view',battery:'12V battery exploded view',lamp:'Headlamp exploded view',wiper:'Wiper blade exploded view',airFilter:'Engine air filter exploded view',cabinFilter:'Cabin / pollen filter exploded view',exhaust:'Exhaust system exploded view'};
const FINDINGS=[
{id:'tyre-fl',icon:'◉',category:'Tyres',module:'tyre',title:'Front left tyre',location:'Nearside front',measurementLabel:'Tread depth',value:1.3,unit:'mm',min:0,max:8,red:1.6,amber:3,direction:'lowBad',condition:'Uneven wear',recommendation:'Replace',price:145,note:'NSF tyre measured at 1.3 mm across principal grooves.',found:'The front left tyre has worn below the legal tread limit.',why:'Tyre tread helps the vehicle grip the road and clear standing water. Low tread can reduce wet-weather grip and increase stopping distance.',history:[5.6,4.2,2.8,1.3],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'brake-rr',icon:'◎',category:'Brakes',module:'brake',title:'Rear right brake pads',location:'Offside rear',measurementLabel:'Pad thickness',value:3.0,unit:'mm',min:0,max:10,red:2,amber:4,direction:'lowBad',condition:'Worn',recommendation:'Replace soon',price:210,note:'OSR brake pad approximately 3 mm remaining.',found:'The rear right brake pads are getting low.',why:'Brake pads are designed to wear as they slow the vehicle. If they become too thin they can affect braking and damage the brake disc.',history:[7.5,6.1,4.4,3.0],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'battery',icon:'⚡',category:'Battery',module:'battery',title:'12V battery',location:'Engine bay',measurementLabel:'State of health',value:71,unit:'%',min:0,max:100,red:50,amber:75,direction:'lowBad',condition:'Reduced performance',recommendation:'Monitor',price:189,note:'Battery tester reports 71% state of health. Charging system normal.',found:'The battery is still usable but its health is starting to decline.',why:'The 12V battery powers vehicle electronics and provides the energy needed to start the vehicle. A weakening battery can eventually lead to slow or failed starting.',history:[94,87,79,71],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'lamp-fr',icon:'✦',category:'Lighting',module:'lamp',title:'Front right headlamp',location:'Offside front',measurementLabel:'Relative light output',value:72,unit:'%',min:0,max:100,red:50,amber:80,direction:'lowBad',condition:'Reduced performance',recommendation:'Repair',price:65,note:'OSF headlamp output visually reduced compared with NSF.',found:'The front right headlamp is producing less light than expected.',why:'Headlamps help you see the road and help other road users see you. Reduced output can affect night-time visibility and may become an MOT issue.',history:[100,94,83,72],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'wiper-front',icon:'⌁',category:'Wipers',module:'wiper',title:'Front wiper blades',location:'Windscreen',measurementLabel:'Blade condition',value:45,unit:'%',min:0,max:100,red:30,amber:60,direction:'lowBad',condition:'Worn',recommendation:'Replace soon',price:42,note:'Front blades leave visible streaks during wet test.',found:'The front wiper blades are leaving streaks on the windscreen.',why:'Wiper blades need to clear water cleanly so you can see properly in rain. Worn rubber can smear the screen instead.',history:[100,82,65,45],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'air-filter',icon:'▤',category:'Service',module:'airFilter',title:'Engine air filter',location:'Engine bay',measurementLabel:'Filter condition',value:52,unit:'%',min:0,max:100,red:25,amber:60,direction:'lowBad',condition:'Worn',recommendation:'Replace soon',price:58,note:'Filter element visibly contaminated with dust and debris.',found:'The engine air filter is becoming dirty and restricted.',why:'The air filter helps keep dirt out of the engine. A heavily contaminated filter can restrict airflow and reduce efficiency.',history:[100,88,70,52],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'cabin-filter',icon:'▥',category:'Service',module:'cabinFilter',title:'Cabin pollen filter',location:'Passenger compartment',measurementLabel:'Filter condition',value:40,unit:'%',min:0,max:100,red:25,amber:60,direction:'lowBad',condition:'Worn',recommendation:'Replace soon',price:49,note:'Pollen filter visibly dark with debris trapped in pleats.',found:'The cabin pollen filter is dirty.',why:'This filter cleans the air entering the cabin. When it becomes blocked it can reduce airflow and allow more dust and pollen through.',history:[100,85,61,40],historyDates:['Mar 25','Sep 25','Mar 26','Today']},
{id:'exhaust',icon:'≈',category:'Exhaust',module:'exhaust',title:'Rear exhaust section',location:'Underbody',measurementLabel:'Condition score',value:58,unit:'%',min:0,max:100,red:30,amber:65,direction:'lowBad',condition:'Corroded',recommendation:'Monitor',price:260,note:'Surface corrosion visible on rear silencer and joint. No major leak detected.',found:'The rear exhaust section is showing corrosion.',why:'The exhaust carries gases safely away from the vehicle. Corrosion can eventually lead to leaks, increased noise or an MOT failure.',history:[100,88,72,58],historyDates:['Mar 25','Sep 25','Mar 26','Today']}
];
const EXTERIOR_IDS=new Set(['tyre-fl','brake-rr','lamp-fr','wiper-front']);
const state=(()=>{try{return JSON.parse(localStorage.getItem('drivewellV4State'))||{findings:structuredClone(FINDINGS),decisions:{},messages:[]}}catch{return{findings:structuredClone(FINDINGS),decisions:{},messages:[]}}})();
if(!state.messages.length)state.messages=[{id:'m1',person:'Sarah Mitchell',initials:'SM',vehicle:'2024 Example SUV',time:'2 min ago',finding:'Front tyres',text:'Can you confirm if this tyre replacement includes alignment?'},{id:'m2',person:'James Carter',initials:'JC',vehicle:'2022 Family SUV',time:'18 min ago',finding:'Front brake pads',text:'Approved front brake pads and wiper blades.'},{id:'m3',person:'Priya Desai',initials:'PD',vehicle:'2023 Saloon',time:'1 hour ago',finding:'12V battery',text:'Is the battery covered by a warranty?'}];
let evidenceUrls={},selectedFindingId=state.findings[0].id,selectedTechId=state.findings[0].id,selectedConversation=0;
const persist=()=>localStorage.setItem('drivewellV4State',JSON.stringify(state));
const findingById=id=>state.findings.find(f=>f.id===id);
function severityFor(f){if(f.direction==='lowBad'){if(f.value<=f.red)return'red';if(f.value<=f.amber)return'amber';return'green'}if(f.value>=f.red)return'red';if(f.value>=f.amber)return'amber';return'green'}
const severityLabel=s=>s==='red'?'Urgent':s==='amber'?'Attention':'Healthy';
function recommendationText(f){const s=severityFor(f);if(s==='red')return`${f.recommendation}. This item needs dealing with before normal use.`;if(s==='amber')return`${f.recommendation}. It is not shown as an immediate stop-driving issue, but it should be planned.`;return'No action is currently required beyond routine monitoring.'}
function toast(text){const e=$('toast');e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2000)}
function routeTo(route){document.querySelectorAll('.route').forEach(r=>r.classList.toggle('active',r.id===`route-${route}`));document.querySelectorAll('.nav-button').forEach(n=>n.classList.toggle('active',n.dataset.route===route));$('pageTitle').textContent={dashboard:'Manager Dashboard',inspection:'Technician Inspection',report:'Vehicle Health Report',communications:'Communications & Approvals'}[route]||'DriveWell';if(route==='dashboard')renderDashboard();if(route==='inspection')renderTechnician();if(route==='report'){renderCustomer();requestAnimationFrame(resizeViewer)}if(route==='communications')renderCommunications()}
document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>routeTo(b.dataset.route)));
function renderDashboard(){$('urgentCount').textContent=state.findings.filter(f=>severityFor(f)==='red').length;$('attentionCount').textContent=state.findings.filter(f=>severityFor(f)==='amber').length;const a=Object.values(state.decisions).filter(d=>d.action==='approved').length;$('reportState').textContent=a?`${a} item${a===1?'':'s'} approved`:'Awaiting decision'}
function techButton(f){const s=severityFor(f);return`<button class="tech-component ${f.id===selectedTechId?'active':''}" data-tech="${f.id}" type="button"><span class="tech-component-icon">${f.icon}</span><span><strong>${f.title}</strong><small>${f.value} ${f.unit} · ${f.condition}</small></span><span class="severity ${s}">${severityLabel(s)}</span></button>`}
function renderTechnician(){$('techComponentList').innerHTML=state.findings.map(techButton).join('');document.querySelectorAll('[data-tech]').forEach(b=>b.addEventListener('click',()=>{selectedTechId=b.dataset.tech;renderTechnician()}));const f=findingById(selectedTechId),s=severityFor(f);$('techCategory').textContent=f.category;$('techTitle').textContent=f.title;$('techLocation').textContent=f.location;$('techAutoSeverity').className=`severity ${s}`;$('techAutoSeverity').textContent=`${severityLabel(s)} · automatic`;$('measurementFieldLabel').textContent=f.measurementLabel;$('techMeasurement').value=f.value;$('techUnit').textContent=f.unit;$('techCondition').value=f.condition;$('techRecommendation').value=f.recommendation;$('techNote').value=f.note||'';$('techModuleName').textContent=MODULE_LABELS[f.module];$('evidenceFileName').textContent=f.evidenceName||'No additional evidence selected';$('captureProgress').textContent=`${state.findings.length} / ${state.findings.length}`;$('captureSaved').textContent=''}
$('techMeasurement').addEventListener('input',()=>{const f={...findingById(selectedTechId),value:Number($('techMeasurement').value)},s=severityFor(f);$('techAutoSeverity').className=`severity ${s}`;$('techAutoSeverity').textContent=`${severityLabel(s)} · automatic`});
$('evidenceInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;evidenceUrls[selectedTechId]=URL.createObjectURL(file);$('evidenceFileName').textContent=file.name});
$('saveFinding').addEventListener('click',()=>{const f=findingById(selectedTechId);f.value=Number($('techMeasurement').value);f.condition=$('techCondition').value;f.recommendation=$('techRecommendation').value;f.note=$('techNote').value.trim();const file=$('evidenceInput').files[0];if(file)f.evidenceName=file.name;persist();$('captureSaved').textContent='Saved · customer report updated';toast(`${f.title} saved`);renderTechnician()});
function measurementPct(f){return Math.max(0,Math.min(100,((f.value-f.min)/(f.max-f.min))*100))}
function findingCard(f){const s=severityFor(f);return`<button class="finding-card ${f.id===selectedFindingId?'active':''}" data-finding="${f.id}" type="button"><span class="finding-card-icon">${f.icon}</span><span><strong>${f.title}</strong><small>${f.value} ${f.unit} · ${severityLabel(s)}</small></span></button>`}
function historySvg(f){const w=400,h=88,px=22,py=13,uw=w-px*2,uh=h-py*2-13,x=i=>px+uw*(i/(f.history.length-1)),y=v=>py+uh*(1-(v-f.min)/(f.max-f.min)),pts=f.history.map((v,i)=>`${x(i)},${y(v)}`).join(' '),dots=f.history.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v)}" r="${i===f.history.length-1?4.6:3}" fill="${i===f.history.length-1?(severityFor(f)==='red'?'#cd4551':'#b87914'):'#2f73e4'}" stroke="#fff" stroke-width="2"/>`).join(''),labels=f.historyDates.map((d,i)=>`<text x="${x(i)}" y="${h-3}" text-anchor="middle" font-size="7" fill="#7f8d9e">${d}</text>`).join('');return`<svg viewBox="0 0 ${w} ${h}"><polyline points="${pts}" fill="none" stroke="#2f73e4" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/>${dots}${labels}</svg>`}
function evidenceSvg(f){const s=severityFor(f),col=s==='red'?'#cd4551':s==='amber'?'#ba7b15':'#26966b',tag=f.module==='tyre'?'TREAD':f.module==='brake'?'PAD':f.module==='battery'?'SOH':f.module==='lamp'?'OUTPUT':f.module==='wiper'?'WIPE':f.module==='airFilter'?'AIR':f.module==='cabinFilter'?'CABIN':'EXHAUST';return`<svg viewBox="0 0 420 150"><defs><linearGradient id="ev-${f.id}" x1="0" x2="1"><stop stop-color="#1b2837"/><stop offset="1" stop-color="#09111b"/></linearGradient></defs><rect width="420" height="150" rx="12" fill="url(#ev-${f.id})"/><rect x="18" y="18" width="180" height="114" rx="11" fill="#263647"/><circle cx="108" cy="75" r="42" fill="none" stroke="#8898aa" stroke-width="13"/><path d="M74 75h68M108 41v68" stroke="#405166" stroke-width="7"/><rect x="226" y="28" width="154" height="31" rx="15" fill="${col}" opacity=".2"/><text x="303" y="49" fill="${col}" font-size="13" font-weight="800" text-anchor="middle">${tag}</text><text x="226" y="91" fill="#f4f7fb" font-size="29" font-weight="900">${f.value} ${f.unit}</text><text x="226" y="114" fill="#a5b2c1" font-size="11">${f.condition}</text></svg>`}
function renderCustomer(){$('customerFindings').innerHTML=state.findings.map(findingCard).join('');document.querySelectorAll('[data-finding]').forEach(b=>b.addEventListener('click',()=>selectFinding(b.dataset.finding,true)));renderSelected(false)}
function renderSelected(change3d=true){const f=findingById(selectedFindingId),s=severityFor(f);$('reportSeverity').className=`severity ${s}`;$('reportSeverity').textContent=severityLabel(s);$('reportTitle').textContent=f.title;$('reportLocation').textContent=f.location;$('reportPrice').textContent=money(f.price);$('reportMeasurementLabel').textContent=f.measurementLabel;$('reportMeasurement').textContent=Number.isInteger(f.value)?f.value:f.value.toFixed(1);$('reportUnit').textContent=f.unit;$('measurementMarker').style.left=`${measurementPct(f)}%`;$('reportFound').textContent=f.found;$('reportWhy').textContent=f.why;$('reportRecommendationText').textContent=recommendationText(f);$('reportEvidenceTitle').textContent=f.evidenceName||'Sample workshop evidence';const src=evidenceUrls[f.id];$('reportEvidenceVisual').innerHTML=src?`<img src="${src}" alt="Technician evidence">`:evidenceSvg(f);const delta=f.history.at(-1)-f.history.at(-2);$('historyDelta').textContent=`${delta>0?'+':''}${delta.toFixed(1)} ${f.unit}`;$('historyChart').innerHTML=historySvg(f);$('approveAmount').textContent=money(f.price);const d=state.decisions[f.id];$('decisionStatus').textContent=d?d.action==='approved'?'Approved by customer':d.action==='deferred'?'Deferred by customer':'Customer asked a question':'';document.querySelectorAll('.finding-card').forEach(c=>c.classList.toggle('active',c.dataset.finding===f.id));if(change3d)focusFinding(f)}
function selectFinding(id,show3d=true){selectedFindingId=id;renderSelected(show3d)}
function decide(action){const f=findingById(selectedFindingId);state.decisions[f.id]={action,time:new Date().toISOString()};if(action==='question')state.messages.unshift({id:`own-${Date.now()}`,person:'Alex Morgan',initials:'AM',vehicle:'2021 Example SUV',time:'just now',finding:f.title,text:`I have a question about the ${f.title.toLowerCase()} recommendation.`});persist();renderSelected(false);renderDashboard();toast(action==='approved'?'Work approved':action==='deferred'?'Item deferred':'Question sent')}
$('approveBtn').addEventListener('click',()=>decide('approved'));$('askBtn').addEventListener('click',()=>decide('question'));$('deferBtn').addEventListener('click',()=>decide('deferred'));
function renderCommunications(){const own=Object.entries(state.decisions).map(([id,d])=>{const f=findingById(id);return{id:`d-${id}`,person:'Alex Morgan',initials:'AM',vehicle:'AB12 CDE',time:'just now',finding:f.title,text:d.action==='approved'?`Approved ${f.title}.`:d.action==='deferred'?`Deferred ${f.title} for now.`:`Asked a question about ${f.title}.`}}),feed=[...own,...state.messages];$('conversationFeed').innerHTML=feed.map((m,i)=>`<button class="conversation-row ${i===selectedConversation?'active':''}" data-conv="${i}"><span class="person-avatar">${m.initials}</span><span><strong>${m.person}</strong><small>${m.vehicle} · ${m.finding}</small><p>${m.text}</p></span><time>${m.time}</time></button>`).join('');document.querySelectorAll('[data-conv]').forEach(b=>b.addEventListener('click',()=>{selectedConversation=Number(b.dataset.conv);renderCommunications()}));const current=feed[selectedConversation]||feed[0];if(current){$('conversationFinding').textContent=current.finding;const f=state.findings.find(x=>x.title===current.finding);$('conversationPrice').textContent=f?money(f.price):'';$('conversationMessages').innerHTML=`<div class="message customer">${current.text}<small>${current.time}</small></div>`}const ds=Object.values(state.decisions);$('commApproved').textContent=6+ds.filter(d=>d.action==='approved').length;$('commQuestions').textContent=2+ds.filter(d=>d.action==='question').length;$('commAwaiting').textContent=Math.max(0,7-ds.length)}
$('sendReply').addEventListener('click',()=>{const text=$('replyText').value.trim();if(!text)return;const msg=document.createElement('div');msg.className='message dealer';msg.innerHTML=`${text}<small>just now</small>`;$('conversationMessages').appendChild(msg);$('replyText').value='';toast('Reply added')});

// --- 3D ---
const viewer=$('viewer'),scene=new THREE.Scene();scene.background=new THREE.Color(0x08111b);scene.fog=new THREE.Fog(0x08111b,10,28);const camera=new THREE.PerspectiveCamera(34,1,.05,100);camera.position.set(5.0,2.25,5.5);const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.03;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewer.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=2.5;controls.maxDistance=9;controls.maxPolarAngle=Math.PI/1.95;controls.target.set(0,.78,0);
scene.add(new THREE.HemisphereLight(0xeaf2ff,0x09101a,1.45));const key=new THREE.DirectionalLight(0xfffbf3,2.9);key.position.set(4.6,6.5,5.3);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const fill=new THREE.DirectionalLight(0x7fa8ff,1.05);fill.position.set(-5,2.8,-3.2);scene.add(fill);const rim=new THREE.DirectionalLight(0xffffff,1.15);rim.position.set(-3,4.5,5.5);scene.add(rim);const floor=new THREE.Mesh(new THREE.PlaneGeometry(22,22),new THREE.MeshStandardMaterial({color:0x111c2b,roughness:.98}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(3.6,3.62,96),new THREE.MeshBasicMaterial({color:0x315483,transparent:true,opacity:.5,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.004;scene.add(ring);
const vehicleRoot=new THREE.Group(),carGroup=new THREE.Group(),hotspotRoot=new THREE.Group(),moduleRoot=new THREE.Group();scene.add(vehicleRoot);vehicleRoot.add(carGroup,hotspotRoot);scene.add(moduleRoot);moduleRoot.visible=false;let vehicleModel=null,hotspots=[],hoveredHotspot=null,selectedHotspot=null,pointerDown={x:0,y:0},activeParts=[],explodeStart=0,exploding=false,cameraTween=null,pendingExplode=null;
const mat=(c,metal=.25,rough=.45)=>new THREE.MeshStandardMaterial({color:c,metalness:metal,roughness:rough});const glass=()=>new THREE.MeshPhysicalMaterial({color:0x26384b,transparent:true,opacity:.55,roughness:.08,metalness:.05,clearcoat:.8,clearcoatRoughness:.1});function mesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;return o}function part(o,offset={},highlight=false){o.userData.base=o.position.clone();o.userData.offset=new THREE.Vector3(offset.x||0,offset.y||0,offset.z||0);o.userData.highlight=highlight;activeParts.push(o);moduleRoot.add(o);return o}function clearModule(){while(moduleRoot.children.length){const c=moduleRoot.children.pop();c.traverse?.(o=>{if(o.geometry)o.geometry.dispose?.();if(o.material)(Array.isArray(o.material)?o.material:[o.material]).forEach(mm=>mm.dispose?.())})}activeParts=[]}
function stage(){const p=mesh(new THREE.CylinderGeometry(3.05,3.18,.22,72),mat(0x111d2b,.12,.9),0,.05,0);part(p);const p2=mesh(new THREE.CylinderGeometry(2.38,2.55,.06,72),mat(0x263c5c,.08,.82),0,.2,0);part(p2)}
function treadBlocks(group,r=1.07,count=26){for(let i=0;i<count;i++){const a=i*Math.PI*2/count,b=mesh(new THREE.BoxGeometry(.18,.15,.31),mat(0x252a30,.03,.9),0,Math.cos(a)*r,Math.sin(a)*r);b.rotation.x=a;group.add(b)}}
function buildTyre(){stage();const rubber=mat(0x11161b,.02,.87),alloy=mat(0xaab3bd,.85,.25),steel=mat(0x7d8792,.6,.33),issue=mat(0xcc4551,.15,.5);const tyreG=new THREE.Group();tyreG.position.set(0,1.18,0);const tyre=mesh(new THREE.TorusGeometry(1.05,.34,30,82),rubber);tyre.rotation.y=Math.PI/2;tyreG.add(tyre);treadBlocks(tyreG);part(tyreG,{x:-1.5});const rim=mesh(new THREE.CylinderGeometry(.73,.73,.25,56),alloy,0,1.18,0);rim.rotation.z=Math.PI/2;part(rim,{x:-.5});for(let i=0;i<7;i++){const s=mesh(new THREE.BoxGeometry(.11,.58,.10),alloy,0,1.18,0);s.rotation.z=Math.PI/2;s.rotation.x=i*Math.PI*2/7;part(s,{x:-.5})}const disc=mesh(new THREE.CylinderGeometry(.48,.48,.11,52),steel,0,1.18,0);disc.rotation.z=Math.PI/2;part(disc,{x:.28});const hub=mesh(new THREE.CylinderGeometry(.18,.18,.38,28),steel,0,1.18,0);hub.rotation.z=Math.PI/2;part(hub,{x:.82});const patch=mesh(new THREE.TorusGeometry(1.06,.075,12,64),issue,0,1.18,0);patch.rotation.y=Math.PI/2;part(patch,{x:-1.78},true)}
function buildBrake(){stage();const steel=mat(0xaab1b9,.78,.28),dark=mat(0x273039,.26,.52),cal=mat(0x8e2630,.42,.35),pad=mat(0xd25a64,.14,.48),ghost=new THREE.MeshPhysicalMaterial({color:0x4b5562,transparent:true,opacity:.22,roughness:.7});const wheel=mesh(new THREE.TorusGeometry(1.18,.25,24,64),ghost,-.7,1.18,0);wheel.rotation.y=Math.PI/2;part(wheel,{x:-1.35});const disc=mesh(new THREE.CylinderGeometry(1.02,1.02,.16,72),steel,0,1.18,0);disc.rotation.z=Math.PI/2;part(disc,{x:-.55});const bell=mesh(new THREE.CylinderGeometry(.32,.32,.36,36),dark,0,1.18,0);bell.rotation.z=Math.PI/2;part(bell,{x:-.1});const p1=mesh(new THREE.BoxGeometry(.14,.86,.36),pad,.4,1.18,.31);part(p1,{x:.8,z:.34},true);const p2=mesh(new THREE.BoxGeometry(.14,.86,.36),pad,.4,1.18,-.31);part(p2,{x:.8,z:-.34},true);const carrier=mesh(new THREE.BoxGeometry(.20,1.28,.94),dark,.8,1.18,0);carrier.rotation.z=.09;part(carrier,{x:1.2});const caliper=mesh(new THREE.BoxGeometry(.58,1.38,.88),cal,1.1,1.18,0);caliper.rotation.z=.11;part(caliper,{x:1.6})}
function buildBattery(){stage();const shell=mat(0x202a34,.08,.64),top=mat(0x0e151e,.08,.5),plate=mat(0x7c8791,.62,.33);const body=mesh(new THREE.BoxGeometry(2.45,1.26,1.62),shell,0,1.08,0);part(body,{x:-.36});const cover=mesh(new THREE.BoxGeometry(2.30,.17,1.47),top,0,1.81,0);part(cover,{y:.64});const tp=mesh(new THREE.CylinderGeometry(.14,.14,.27,24),mat(0xc3404a,.56,.24),-.68,1.95,.34);part(tp,{x:-.4,y:.7},true);const tn=mesh(new THREE.CylinderGeometry(.14,.14,.27,24),mat(0xb5bec8,.62,.24),.68,1.95,.34);part(tn,{x:.4,y:.7});for(let i=-2;i<=2;i++){const cell=mesh(new THREE.BoxGeometry(.20,1.00,1.22),plate,i*.32,1.08,0);part(cell,{x:i*.24,y:.03})}const strap=mesh(new THREE.BoxGeometry(2.65,.11,.18),mat(0x52616f,.32,.43),0,1.53,0);part(strap,{z:.48})}
function buildLamp(){stage();const housing=mesh(new THREE.BoxGeometry(2.45,1.06,.78),mat(0x202c38,.2,.43),0,1.25,0);housing.rotation.y=-.1;part(housing,{x:-.72});const lens=mesh(new THREE.BoxGeometry(2.40,.98,.11),glass(),0,1.25,.43);part(lens,{z:1.03});[-.64,.05,.68].forEach((x,i)=>{const ref=mesh(new THREE.CylinderGeometry(i===2?.24:.28,i===2?.38:.45,.34,34),mat(0xc1c9d2,.88,.16),x,1.25,.08);ref.rotation.x=Math.PI/2;part(ref,{z:.44})});const bulb=mesh(new THREE.SphereGeometry(.17,28,20),mat(0xffbd46,.08,.18),.68,1.25,.28);part(bulb,{x:.55,z:.82},true);const ecu=mesh(new THREE.BoxGeometry(.64,.44,.18),mat(0x394756,.26,.42),-.78,.78,-.15);part(ecu,{x:-.42,z:-.45})}
function buildWiper(){stage();const screen=mesh(new THREE.BoxGeometry(2.95,1.85,.07),glass(),0,1.42,-.06);screen.rotation.x=-.42;part(screen,{y:.18,z:-.2});const arm=mesh(new THREE.BoxGeometry(2.42,.12,.12),mat(0x2b3239,.22,.58),0,1.24,.06);arm.rotation.z=.18;arm.rotation.x=-.34;part(arm,{y:.28});const blade=mesh(new THREE.BoxGeometry(2.95,.10,.22),mat(0x13181e,.04,.82),.18,.87,.25);blade.rotation.z=-.03;blade.rotation.x=-.34;part(blade,{y:-.45,z:.17},true);const rubber=mesh(new THREE.BoxGeometry(2.77,.04,.07),mat(0xc84b55,.04,.74),.18,.80,.31);rubber.rotation.z=-.03;rubber.rotation.x=-.34;part(rubber,{y:-.61,z:.26},true);const pivot=mesh(new THREE.CylinderGeometry(.18,.18,.2,26),mat(0xa0aab4,.68,.3),-1.04,1.00,-.02);pivot.rotation.x=Math.PI/2;part(pivot,{x:-.34})}
function filterGroup(w,h,d,dirty=true){const g=new THREE.Group(),frame=mesh(new THREE.BoxGeometry(w,h,d),mat(0x2c343d,.14,.56));g.add(frame);for(let i=0;i<16;i++){const p=mesh(new THREE.BoxGeometry(w*.80,.028,d*1.03),mat(dirty?0x8d7b61:0xe7d5aa,.04,.82),0,-h*.41+i*(h*.82/15),0);g.add(p)}return g}
function buildAirFilter(){stage();const box=mesh(new THREE.BoxGeometry(2.95,1.55,1.88),mat(0x222b35,.08,.64),0,1.06,0);part(box,{x:-1.0});const filter=filterGroup(2.42,1.14,.32,true);filter.position.set(.12,1.06,0);part(filter,{x:1.52},true);const lid=mesh(new THREE.BoxGeometry(3.02,.15,1.95),mat(0x101821,.08,.63),0,1.89,0);part(lid,{y:.70});const tube=mesh(new THREE.CylinderGeometry(.28,.28,1.25,30),mat(0x1b242e,.08,.7),-1.8,1.0,0);tube.rotation.z=Math.PI/2;part(tube,{x:-.8})}
function buildCabinFilter(){stage();const housing=mesh(new THREE.BoxGeometry(2.92,1.60,1.15),mat(0x2d3741,.08,.58),0,1.05,0);part(housing,{x:-1.02});const filter=filterGroup(2.50,1.22,.35,true);filter.position.set(.12,1.05,0);part(filter,{x:1.52},true);const cover=mesh(new THREE.BoxGeometry(.18,1.41,1.10),mat(0x111922,.08,.6),1.55,1.05,0);part(cover,{x:1.08})}
function buildExhaust(){stage();const pipe=mat(0x9aa3ac,.70,.35),dark=mat(0x68717a,.55,.39),rust=mat(0xb66a47,.27,.58);const front=mesh(new THREE.CylinderGeometry(.14,.14,1.95,26),pipe,-1.60,1.02,0);front.rotation.z=Math.PI/2;part(front,{x:-1.05});const cat=mesh(new THREE.CylinderGeometry(.34,.34,.84,30),dark,-.45,1.02,0);cat.rotation.z=Math.PI/2;part(cat,{x:-.35});const mid=mesh(new THREE.CylinderGeometry(.14,.14,1.48,26),pipe,.52,1.02,0);mid.rotation.z=Math.PI/2;part(mid,{x:.26});const silencer=mesh(new THREE.CylinderGeometry(.51,.51,1.30,32),rust,1.77,1.02,0);silencer.rotation.z=Math.PI/2;part(silencer,{x:1.05},true);const tail=mesh(new THREE.CylinderGeometry(.13,.13,.82,22),pipe,2.92,1.02,0);tail.rotation.z=Math.PI/2;part(tail,{x:1.48});const clamp=mesh(new THREE.TorusGeometry(.21,.027,10,34),mat(0xd4dae0,.38,.27),1.08,1.02,0);clamp.rotation.y=Math.PI/2;part(clamp,{x:.56})}
const builders={tyre:buildTyre,brake:buildBrake,battery:buildBattery,lamp:buildLamp,wiper:buildWiper,airFilter:buildAirFilter,cabinFilter:buildCabinFilter,exhaust:buildExhaust};
function hotspotMaterial(col){return new THREE.MeshStandardMaterial({color:col,emissive:col,emissiveIntensity:.55,transparent:true,opacity:1})}
function addHotspot(f,pos){const s=severityFor(f),col=s==='red'?0xd24c58:s==='amber'?0xd89522:0x2ca273,g=new THREE.Group();g.position.copy(pos);g.userData.findingId=f.id;const outer=mesh(new THREE.TorusGeometry(.105,.018,10,28),hotspotMaterial(col));outer.rotation.x=Math.PI/2;const dot=mesh(new THREE.SphereGeometry(.052,18,14),hotspotMaterial(col));g.add(outer,dot);hotspotRoot.add(g);hotspots.push(g)}
function rebuildHotspots(){while(hotspotRoot.children.length)hotspotRoot.remove(hotspotRoot.children[0]);hotspots=[];const pos={'tyre-fl':[-1.15,.60,1.36],'brake-rr':[1.14,.62,-1.29],'lamp-fr':[1.18,1.02,1.38],'wiper-front':[.08,1.49,.64]};state.findings.filter(f=>EXTERIOR_IDS.has(f.id)).forEach(f=>addHotspot(f,new THREE.Vector3(...pos[f.id])))}
const focusPoses={'tyre-fl':{cam:[3.6,1.45,3.5],target:[-1.05,.62,1.12]},'brake-rr':{cam:[-3.2,1.5,-3.3],target:[1.05,.62,-1.05]},'lamp-fr':{cam:[3.4,1.7,3.2],target:[1.0,1.05,1.05]},'wiper-front':{cam:[2.6,2.2,3.6],target:[.05,1.40,.45]}};
const loader=new GLTFLoader();loader.load('./assets/lowpoly_generic_suv.glb',gltf=>{vehicleModel=gltf.scene;vehicleModel.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;const n=o.name.toLowerCase();if(n.includes('body'))o.material=new THREE.MeshPhysicalMaterial({color:0x7b8796,metalness:.58,roughness:.28,clearcoat:.72,clearcoatRoughness:.12});else if(n.includes('glass'))o.material=glass();else if(o.material)o.material=o.material.clone()});carGroup.add(vehicleModel);const b=new THREE.Box3().setFromObject(vehicleModel),size=b.getSize(new THREE.Vector3()),scale=5.15/Math.max(size.x,size.z);vehicleModel.scale.setScalar(scale);const b2=new THREE.Box3().setFromObject(vehicleModel),c=b2.getCenter(new THREE.Vector3());vehicleModel.position.sub(c);vehicleModel.position.y-=b2.min.y;carGroup.rotation.y=.72;hotspotRoot.rotation.y=.72;rebuildHotspots();resetVehicleView();$('viewerLoading').classList.add('hidden')},undefined,()=>{$('viewerLoading').classList.add('hidden');$('viewerError').classList.remove('hidden')});
function setHotspotOpacity(selectedId=null){hotspots.forEach(g=>{const active=!selectedId||g.userData.findingId===selectedId;g.children.forEach(ch=>{if(ch.material){ch.material.opacity=active?1:.12;ch.material.transparent=true}})})}
function startCameraTween(endPos,endTarget,duration=620,onDone){cameraTween={start:performance.now(),duration,startPos:camera.position.clone(),startTarget:controls.target.clone(),endPos:new THREE.Vector3(...endPos),endTarget:new THREE.Vector3(...endTarget),onDone}}
function resetVehicleView(){pendingExplode=null;cameraTween=null;moduleRoot.visible=false;vehicleRoot.visible=true;setHotspotOpacity();selectedHotspot=null;hoveredHotspot=null;$('hotspotCallout').classList.add('hidden');$('explodedCaption').classList.add('hidden');$('backToVehicle').classList.add('hidden');$('viewerModeLabel').textContent='VEHICLE OVERVIEW';$('viewerTitle').textContent='Tap an issue to explore it';camera.position.set(5.0,2.25,5.5);controls.target.set(0,.78,0);controls.enabled=true;controls.update()}
$('backToVehicle').addEventListener('click',resetVehicleView);$('resetView').addEventListener('click',()=>{if(moduleRoot.visible){camera.position.set(4.6,2.4,5.25);controls.target.set(0,1.03,0);controls.update()}else resetVehicleView()});
function showCallout(f,group){const s=severityFor(f),world=new THREE.Vector3();group.getWorldPosition(world);const projected=world.clone().project(camera),rect=viewer.getBoundingClientRect();const x=(projected.x*.5+.5)*rect.width,y=(-projected.y*.5+.5)*rect.height;const el=$('hotspotCallout');el.style.left=`${x}px`;el.style.top=`${y}px`;el.classList.remove('hidden');$('hotspotStatus').textContent=severityLabel(s).toUpperCase();$('hotspotStatus').style.color=s==='red'?'#ff7f89':'#ffbd5d';$('hotspotTitle').textContent=f.title;$('hotspotValue').textContent=`${f.value} ${f.unit} · tap to explore`}
function hideCallout(){if(!selectedHotspot)$('hotspotCallout').classList.add('hidden')}
function focusFinding(f){selectedFindingId=f.id;if(EXTERIOR_IDS.has(f.id)){selectedHotspot=f.id;setHotspotOpacity(f.id);const g=hotspots.find(h=>h.userData.findingId===f.id);if(g)showCallout(f,g);const pose=focusPoses[f.id];controls.enabled=false;startCameraTween(pose.cam,pose.target,620,()=>{pendingExplode={f,at:performance.now()+180}})}else{showExploded(f)}}
function showExploded(f){pendingExplode=null;cameraTween=null;clearModule();vehicleRoot.visible=false;moduleRoot.visible=true;$('hotspotCallout').classList.add('hidden');$('explodedCaption').classList.remove('hidden');$('explodedCaptionTitle').textContent=f.title;$('backToVehicle').classList.remove('hidden');$('viewerModeLabel').textContent='EXPLODED COMPONENT';$('viewerTitle').textContent=f.title;builders[f.module]?.();explodeStart=performance.now();exploding=true;controls.enabled=true;camera.position.set(4.6,2.4,5.25);controls.target.set(0,1.03,0);controls.update()}
renderer.domElement.addEventListener('pointerdown',e=>pointerDown={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointermove',e=>{if(moduleRoot.visible||selectedHotspot)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(hotspotRoot.children,true);let group=null;if(hits.length){let o=hits[0].object;while(o&&!o.userData.findingId)o=o.parent;group=o}if(group!==hoveredHotspot){hoveredHotspot=group;if(group){const f=findingById(group.userData.findingId);showCallout(f,group)}else hideCallout()}});renderer.domElement.addEventListener('pointerleave',()=>{hoveredHotspot=null;hideCallout()});renderer.domElement.addEventListener('pointerup',e=>{if(moduleRoot.visible||Math.hypot(e.clientX-pointerDown.x,e.clientY-pointerDown.y)>8)return;const rect=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-((e.clientY-rect.top)/rect.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(hotspotRoot.children,true);if(!hits.length)return;let o=hits[0].object;while(o&&!o.userData.findingId)o=o.parent;if(o?.userData.findingId){selectedFindingId=o.userData.findingId;renderSelected(true)}});
function resizeViewer(){const r=viewer.getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}window.addEventListener('resize',resizeViewer);resizeViewer();
function animate(now){requestAnimationFrame(animate);if(cameraTween){const p=Math.min(1,(now-cameraTween.start)/cameraTween.duration),e=1-Math.pow(1-p,3);camera.position.lerpVectors(cameraTween.startPos,cameraTween.endPos,e);controls.target.lerpVectors(cameraTween.startTarget,cameraTween.endTarget,e);if(p>=1){const done=cameraTween.onDone;cameraTween=null;done?.()}}if(pendingExplode&&now>=pendingExplode.at)showExploded(pendingExplode.f);if(moduleRoot.visible&&exploding){const p=Math.min(1,(now-explodeStart)/900),e=1-Math.pow(1-p,3);activeParts.forEach((o,i)=>{const b=o.userData.base,off=o.userData.offset;o.position.set(b.x+off.x*e,b.y+off.y*e,b.z+off.z*e);if(o.userData.highlight&&o.material?.emissive){o.material.emissive.setHex(0x7b1e28);o.material.emissiveIntensity=.12+.08*Math.sin(now*.004+i)}});if(p>=1)exploding=false}hotspots.forEach((h,i)=>{const p=1+Math.sin(now*.0035+i)*.06;h.scale.setScalar(p)});if((hoveredHotspot||selectedHotspot)&&!moduleRoot.visible){const id=selectedHotspot||(hoveredHotspot&&hoveredHotspot.userData.findingId),g=hotspots.find(h=>h.userData.findingId===id);if(g)showCallout(findingById(id),g)}controls.update();renderer.render(scene,camera)}requestAnimationFrame(animate);
routeTo('dashboard');renderTechnician();renderCustomer();renderCommunications();
